import { useState, ChangeEvent, FormEvent } from "react"
import styles from "@/styles/Home.module.css"
import Head from "next/head"
import Link from "next/link"

interface regUser {
  email: string
  password: string
}

const LoginForm = () => {
  const [user, setUser] = useState<regUser>({
    email: "",
    password: "",
  })

  const handleChange = (event: ChangeEvent<HTMLInputElement>) => {
    const fieldName = event.target.name
    setUser((prevState) => {
      return { ...prevState, [fieldName]: event.target.value }
    })
  }

  // Det här ska vara en knapp för att logga in
  const handleLogin = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault()
  }

  return (
    <>
      <Head>
        <title>Peppi-Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className=" font-extrabold text-5xl">Välkommen!</h1>
        <br />

        <form onSubmit={handleLogin}>
          <input
            type="text"
            name="email"
            placeholder="Your email..."
            onChange={handleChange}
          />
          <input type="password" name="password" onChange={handleChange} />
          <input
            type="submit"
            value="Logga in"
            className=" text-3xl font-extrabold"
          />
        </form>

        <Link
          href="/schedule"
          className=" text-3xl font-extrabold text-decoration-line: none"
        >
          Logga in
        </Link>
        <hr className=" border border-cyan-400 border-opacity-20" />
        <p className="font-bold text-lg">Eller logga in med</p>
        <br />
        <p className="text-sm font-bold">
          Har du inget konto?{" "}
          <Link href="registerForm" className="text-sm font-bold text-blue-600">
            {" "}
            Registrera dig här
          </Link>
        </p>
      </main>
    </>
  )
}

export default LoginForm
