import { User } from "@/types/User"
import { useState, ChangeEvent, FormEvent } from "react"
import Head from "next/head"
import styles from "@/styles/Home.module.css"
import Link from "next/link"

type RegisterFormProps = {
  onSuccess: () => void
}

const RegisterForm = ({ onSuccess }: RegisterFormProps) => {
  const [user, setUser] = useState<User>({
    email: "",
    password: "",
  })

  const handleChange = (event: ChangeEvent<HTMLInputElement>) => {
    const fieldName = event.target.name
    setUser((prevState) => {
      return { ...prevState, [fieldName]: event.target.value }
    })
  }

  const handleRegister = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault()

    const response = await fetch("/api/register", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(user),
    })
    console.log(response)

    if (response.ok) {
      onSuccess()
    }
  }

  return (
    <div>
      <Head>
        <title>Peppi Register</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className=" font-extrabold text-5xl">Registrera</h1>
        <br />

        <form onSubmit={handleRegister}>
          <input type="text" name="email" placeholder="Enter your email..." />
          <input type="password" name="password" />
          <input type="submit" value="Register" />
        </form>

        <Link href="/" className=" text-3xl font-extrabold">
          Registrera
        </Link>
        <hr className=" border border-cyan-400 border-opacity-20" />
        <p className="font-bold text-lg">Eller registrera dig med</p>
        <br />
        <p className="text-sm font-bold">
          Har du redan ett konto?{" "}
          <Link href="/loginPeppi" className="text-sm font-bold text-blue-600">
            {" "}
            Logga in
          </Link>
        </p>
      </main>
    </div>
  )
}
export default RegisterForm
