import Head from "next/head"
import styles from "@/styles/Home.module.css"
import { useState, useEffect } from "react"

interface Props {
  duration: number
}

const TimerClock: React.FC<Props> = ({ duration }) => {
  const [timeLeft, setTimeLeft] = useState<number>(duration * 60)
  const [isPaused, setIsPaused] = useState<boolean>(true)

  useEffect(() => {
    let intervalId: NodeJS.Timeout | undefined
    if (!isPaused) {
      intervalId = setInterval(() => {
        setTimeLeft((prevTimeLeft) => prevTimeLeft - 1)
      }, 1000)
    }

    return () => {
      if (intervalId) {
        clearInterval(intervalId)
      }
    }
  }, [duration, isPaused])

  useEffect(() => {
    setTimeLeft(duration * 60)
  }, [duration])

  const formatTime = (seconds: number) => {
    const minutes = Math.floor(seconds / 60)
    const remainingSeconds = seconds % 60
    const formattedMinutes = minutes < 10 ? `0${minutes}` : `${minutes}`
    const formattedSeconds =
      remainingSeconds < 10 ? `0${remainingSeconds}` : `${remainingSeconds}`
    return `${formattedMinutes}:${formattedSeconds}`
  }

  const handleStart = () => {
    setIsPaused(false)
  }

  const handlePause = () => {
    setIsPaused(true)
  }

  const handleReset = () => {
    setIsPaused(true)
    setTimeLeft(duration * 60)
  }

  return (
    <div>
      <h1>{formatTime(timeLeft)}</h1>
      {isPaused ? (
        <button onClick={handleStart}>Start</button>
      ) : (
        <button onClick={handlePause}>Pause</button>
      )}
      <button onClick={handleReset}>Reset</button>
    </div>
  )
}

const TimerControls = () => {
  const [duration, setDuration] = useState<number>(15)

  const handleButtonClick = (selectedDuration: number) => {
    setDuration(selectedDuration)
  }

  return (
    <>
      <Head>
        <title>Peppi Timer setup</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.timerBakgrund}>
        <br />
        <br />
        <br />
        <br />
        <div className={styles.timerClock}>
          <br />
          <br />
          <br />
          <br />
          <div className={styles.timerClockFrame}>
            <div className={styles.timerTwelveSpike}>|</div>
            <div className={styles.timerNineSpike}>-</div>
            <div className={styles.timerThreeSpike}>-</div>
            <div className={styles.timerSixSpike}>|</div>
            <div className={styles.timerPeppiFace}></div>
          </div>
          <br />
          <br />
          <br />
        </div>
        Välj tid manuellt
        <br />
        <div className={styles.digitalClock}>00:00</div>
        <br />
        Snabbval
        <br />
        <div className={styles.boxSnabbButton}>
          <button
            onClick={() => handleButtonClick(15)}
            className={styles.timerSnabbButtons}
          >
            15 min
          </button>
          <button
            onClick={() => handleButtonClick(30)}
            className={styles.timerSnabbButtons}
          >
            30 min
          </button>
        </div>
        <div className={styles.boxSnabbButton}>
          <button
            onClick={() => handleButtonClick(45)}
            className={styles.timerSnabbButtons}
          >
            45 min
          </button>
          <button
            onClick={() => handleButtonClick(60)}
            className={styles.timerSnabbButtons}
          >
            60 min
          </button>
        </div>
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
      </div>
    </>
  )
}

export default TimerControls
